FROM fedora:34

RUN dnf -y up

RUN dnf in -y qt6-qtbase-devel gcc gcc-c++ cmake make

RUN adduser builder
RUN echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

RUN echo -e '#!/bin/bash\ncd /CircuitTester/\nmkdir -p linbuild6\ncd linbuild6\ncmake -DCMAKE_BUILD_TYPE=release -DQT_VER=6 ..\nmake -j4' > /bin/build && chmod +x /bin/build
RUN echo -e '#!/bin/bash\ncd /CircuitTester/linbuild6/src/test/\n./test' > /bin/runtest && chmod +x /bin/runtest
